### ISSUE TITLE
 no such file or directory 'credentials.json'

### ISSUE THREAD

**Issue by hdriel** [kurtlocker/sheets-api#1]
In you API , you don't mention any credentials.json file for authorize with it, So it's failed on the sheets.authorize() async function

please update how to use it with no credentials.json file

**Comment by HeavyMedl** [comment]
Hey @hdriel,

The README.md mentions completing Google's [Node.js quickstart](https://developers.google.com/sheets/api/quickstart/nodejs) to acquire a `client_secret.json`. However, that file has been since renamed by Google to `credentials.json` when you download the client configuration after enabling the Google Sheets API. There is no way to interact with Google Sheets without this.

Optionally, you can create an instance of SheetsAPI with an absolute path pointing to `credentials.json`:

```javascript
const sheets = new SheetsAPI('path/to/credentials.json');
```

If no path is specified, google-authorize will attempt to read `credentials.json` relative to your project directory.

Let me know if this helps.

**Comment by HeavyMedl** [comment]
No reply = closing
